### ISSUE TITLE
Trying to load wcs values

### ISSUE THREAD

**Issue by CSwigg** [CSwigg/stellarmass_pca#1]
I'm trying to load in the wcs values from an individual results file with the mask hdu. Here's how I'm doing it in my own ipython terminal (code for this isn't in read_results.py yet, I'm just testing things out now):

```
from astropy import wcs
hdl = fits.open(''8144-3704_res.fits')
w = wcs.WCS(hdl['mask'])
print(w)
```

What I get:

```
WCS Transformation

This transformation has 2 pixel and 2 world dimensions

Array shape (Numpy order): None

Pixel Dim  Data size  Bounds
        0       None  None
        1       None  None

World Dim  Physical Type  Units
        0  None           unknown
        1  None           unknown

Correlation between pixel and world axes:

           Pixel Dim
World Dim    0    1
        0  yes   no
        1   no  yes
```
So it looks like it isn't detecting the pixels I want to transform. Any thoughts @zpace?

**Comment by zpace** [comment]
Evidently, the WCS is not propagated through the results files. This was an oversight by me, but it's possible to get it by other means. Namely, you can use the DAP products (any of the headers should work, just choose one that makes sense and you think isn't likely to change name). This is unfortunate, but not catastrophic. Thanks for raising!

**Comment by CSwigg** [comment]
So would this imply that we expect a user to have the entire /sas/dr16/manga directory mirrored locally? Thanks!

**Comment by zpace** [comment]
It would be necessary to have some other data with WCS info. This could be accomplished by allowing an argument to be passed giving the location of a FITS file with WCS info. Absent that argument (i.e., when that argument is None), the plotter looks in a default location (determined by `$SAS_BASE_DIR`, release version, etc) for the relevant DAP MAPS (one of the formats). Absent that file, the plotter looks for the DRP CUBE. And as a last resort, the image can be shown without any wcs (but raising a warning).

This is just one idea for how to do this, which should be doable using a for loop and try-except.

**Comment by CSwigg** [comment]
Ok that makes sense. Right now I've just been handling the condition where a user does pass in a MAPS file, so I'll make sure to check the others. 

One follow up q – I noticed an attribute self.map_shape. Would this be an okay way to initialize it?

```
self.map_shape = self.pca_out.getdata('Mask').shape
```
Currently in find_pcs.py it is:
```
self.O, self.ivar, self.mask_spax = dered.correct_and_match(
            template_logl=pca.logl, template_dlogl=pca.dlogl,
            method=dered_method, dered_kwargs=dered_kwargs)
self.nl, *self.map_shape = self.O.shape
```

**Comment by zpace** [comment]
yes, that's a good way to do initialize `map_shape`. The mask will always be the same size as any map you want to display
